language: go
go:
  - 1.3
install:
  - go get code.google.com/p/go.crypto/blowfish
  - go get code.google.com/p/go.crypto/cast5
  - go install ./cmd/shadowsocks-local
  - go install ./cmd/shadowsocks-server
script:
  - PATH=$PATH:$HOME/gopath/bin bash -x ./script/test.sh
